language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t douchebag15/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true douchebag15/frontend npm run test
